#!/usr/bin/env bash
# Fills an EMPTY release body; a body the owner wrote (or --generate-notes filled) is
# left alone. Source, in order:
#   1. CHANGELOG.md's `## [Unreleased]` section at the tagged commit (changelog-section.sh,
#      the same lines release.yml's check requires and roll-version.sh dates);
#   2. GitHub's generated notes from the previous stable tag.
#
# Usage: release-notes.sh <tag>   (in a checkout of the tagged commit with its tags)
# Env: GH_TOKEN (contents: write), GITHUB_REPOSITORY.
set -euo pipefail
shopt -s inherit_errexit

tag=${1:?usage: release-notes.sh <tag>}
here=$(dirname "$0")

release=$(gh api "repos/${GITHUB_REPOSITORY}/releases/tags/${tag}")
id=$(jq -r .id <<<"$release")
if [[ -n "$(jq -r '.body // "" | gsub("\\s"; "")' <<<"$release")" ]]; then
  echo "release ${tag} already has notes; leaving them."
  exit 0
fi

body=""
if [[ -f CHANGELOG.md ]]; then
  body=$("${here}/changelog-section.sh" Unreleased CHANGELOG.md 2>/dev/null || true)
  if [[ -n "${body//[[:space:]]/}" ]]; then echo "notes from CHANGELOG.md [Unreleased]"; fi
fi
if [[ -z "${body//[[:space:]]/}" ]]; then
  args=(-f tag_name="$tag")
  if prev=$(git tag -l 'v*' | "${here}/highest-release-tag.sh" --below "$tag"); then
    args+=(-f previous_tag_name="$prev")
  fi
  body=$(gh api -X POST "repos/${GITHUB_REPOSITORY}/releases/generate-notes" "${args[@]}" --jq .body)
  echo "notes generated by GitHub (since ${prev:-the first commit})"
fi
gh api --silent -X PATCH "repos/${GITHUB_REPOSITORY}/releases/${id}" -f body="$body"
printf '%s\n' "$body"
